import { Transaction } from "../types/transactions";

export const Transactions: Transaction[] = [
  {
    id: Date.now().toString(),
    description: "Chicken Wings",
    amount: 100,
    transaction_date: "2023-01-01",
    category: "food",
    type: "expense",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: (Date.now() + 1).toString(),
    description: "End of the year salary",
    amount: 5000,
    transaction_date: "2023-01-02",
    category: "salary",
    type: "income",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: (Date.now() + 2).toString(),
    description: "Rent",
    amount: 1500,
    transaction_date: "2023-01-03",
    category: "rent",
    type: "expense",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: (Date.now() + 3).toString(),
    description: "Groceries",
    amount: 800,
    transaction_date: "2023-01-04",
    category: "groceries",
    type: "expense",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: (Date.now() + 4).toString(),
    description: "Tax Refund",
    amount: 1000,
    transaction_date: "2023-01-05",
    category: "tax refund",
    type: "income",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: (Date.now() + 5).toString(),
    description: "Dining Out",
    amount: 500,
    transaction_date: "2023-01-06",
    category: "dining out",
    type: "expense",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: (Date.now() + 6).toString(),
    description: "Phone Bill",
    amount: 100,
    transaction_date: "2023-01-07",
    category: "phone bill",
    type: "expense",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: (Date.now() + 7).toString(),
    description: "Interest Income",
    amount: 50,
    transaction_date: "2023-01-08",
    category: "interest income",
    type: "income",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: (Date.now() + 8).toString(),
    description: "Car Insurance",
    amount: 200,
    transaction_date: "2023-01-10",
    category: "car insurance",
    type: "expense",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: (Date.now() + 9).toString(),
    description: "Savings",
    amount: 1000,
    transaction_date: "2023-01-10",
    category: "savings",
    type: "income",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
